# Generated by Django 2.2.3 on 2019-07-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questlist',
            name='quest_type',
            field=models.TextField(choices=[('ONCE', 'Разовый'), ('REGULAR', 'Регулярный'), ('DAILY', 'Ежедневный')]),
        ),
    ]
